- name: Install opam using package manager
  become: true
  when: opam_install_method == 'package_manager'
  ansible.builtin.package:
    name: "{{ opam_package_name }}"
    state: present
  timeout: 60
