- name: Install opam using direct install
  when: opam_install_method == 'direct'
  become: true
  block:
    - name: Installing opam external dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ opam_external_dependencies }}"
    - name: Install Opam using direct install script
      expect:
        command: bash -c "sh <(curl -fsSL https://opam.ocaml.org/install.sh)"
        responses:
          Where should it be installed ?: ""
        timeout: 30
        creates: "/usr/local/bin/opam"
