---
- name: Install opam using package manager
  when: opam_install_method == 'package_manager'
  package:
    name: "{{ opam_package_name }}"
    state: present
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Install opam directly
  when: opam_install_method == 'direct'
  expect:
    command: bash -c "sh <(curl -fsSL https://opam.ocaml.org/install.sh)"
    responses:
      Where should it be installed ?: ""
    timeout: 120
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
